<a href="https://colab.research.google.com/github/Song-Hyunsub/Univ_Study/blob/main/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EC%9D%B4%ED%95%B4_%EC%8B%A4%EC%8A%B5/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_5%EC%B0%A8%EC%8B%9C_like_knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

KNN의 특장점 : 간단한 구조, 이해 용이, 구현 용이, 강력한 결과  
서로 비슷한 속성끼리 모이는 경향을 보여줌  
주변 K개의 속성 조사  
가장 많은 투표를 얻은 클래스나 속성 예측  
K값은 주관적이기 때문에 적당한 값을 정해야 함  
KNN(K-인접 이웃) 알고리즘 : 여러 K값으로 테스트 -> 가장 좋은 방법으로 나눈 것  
=> 모든 계산이 이루어진 이후 분류 수행  
'사례 기반 학습' 또는 '메모리 기반 학습'이라고 함  
=> 훈련 데이터에 target값이 존재하므로 '지도 학습'이다.  
* 색깔 공 예시 확인하기!  
Weighted KNN : 거리의 역수나 역수의 제곱의 역수를 가중치를 두어 정확도가 높음  
y = argmax_v (sum_D_x(I(v=y_i)))  
I : Identifier 함수 => 1=참, 0=거짓  
D_x : x를 중심으로 텍스트 제시 (반경 집합)  
argmax_v : 괄호 안 수식의 최대 변수 v(클래스)를 찾는 것  
  
KNN 분류기 실습  
  
호감도 Label 예측 모델 : 범주형 데이터이므로 KNN 분류기(Classifier)로 만듦  
K값을 선택하면서 시행착오를 겪어야 함  
K값에 따라서 분류 결과, 정확도, 신뢰도가 달라짐  
KNeighborsClassifier() 함수 = 분류기로 사용  
Regressor 함수 = 연속형 데이터 예측  
KNeighborsRegressor() = 연속형 값 예측  
데이터 -> 모델 구축 -> 호감도 라벨 예측  
실제 관측 데이터와 얼마나 차이나는가 확인하는 것이 중요!  

In [ ]:
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

#데이터를 읽어오기
like = pd.read_csv('like.csv')
like.columns = ['talk' , 'book' , 'travel' , 'school' , 'tall' , 'skin' , 'muscle' , 'like_level']
like.head()

talk  book  travel  school  tall  skin  muscle like_level
0    30    80      40      40    90    90      50        1타입
1    60    50      70      50    60    60      90        2타입
2    50    40      80      60    50    70      80        2타입
3    90    50      60      30    40    20      30        3타입
4    50    70      30      70    70    80      60        1타입

In [ ]:
#입력과 target데이터를 분리한다. (like_level => 예측해야 하는 target 값 )
x = np.array(like.drop('like_level', axis=1))
print(x.shape)
y = np.array(like.like_level)
print(y.shape)

(14, 7)
(14,)


In [ ]:
x

array([[30, 80, 40, 40, 90, 90, 50],
       [60, 50, 70, 50, 60, 60, 90],
       [50, 40, 80, 60, 50, 70, 80],
       [90, 50, 60, 30, 40, 20, 30],
       [50, 70, 30, 70, 70, 80, 60],
       [70, 30, 60, 40, 40, 40, 30],
       [40, 90, 60, 60, 60, 80, 60],
       [30, 60, 90, 60, 40, 70, 70],
       [80, 40, 20, 80, 60, 40, 50],
       [50, 70, 70, 50, 70, 90, 50],
       [80, 50, 60, 40, 50, 40, 70],
       [30, 70, 30, 90, 70, 80, 60],
       [40, 60, 90, 60, 50, 70, 80],
       [80, 30, 50, 50, 80, 40, 60]], dtype=int64)

In [ ]:
y

array(['1타입', '2타입', '2타입', '3타입', '1타입', '3타입', '1타입', '2타입', '3타입',
       '1타입', '3타입', '1타입', '2타입', '3타입'], dtype=object)

In [ ]:
y.shape , x.shape

((14,), (14, 7))

In [ ]:
#데이터를 정규화한다. (=> 동등한 입장에서 모델을 만들 수 있음)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x)

x = scaler.transform(x)

C:\Users\USER\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [ ]:
x

array([[-1.26962211,  1.34164079, -0.8461218 , -0.98782916,  2.06644812,
         1.29927838, -0.59160798],
       [ 0.21160368, -0.36590203,  0.57536283, -0.3592106 ,  0.04805693,
        -0.09994449,  1.77482393],
       [-0.28213825, -0.93508297,  1.04919104,  0.26940795, -0.62474013,
         0.36646313,  1.18321596],
       [ 1.69282948, -0.36590203,  0.10153462, -1.61644772, -1.29753719,
        -1.96557498, -1.77482393],
       [-0.28213825,  0.77245985, -1.31995001,  0.89802651,  0.720854  ,
         0.83287076,  0.        ],
       [ 0.70534562, -1.50426391,  0.10153462, -0.98782916, -1.29753719,
        -1.03275974, -1.77482393],
       [-0.77588018,  1.91082173,  0.10153462,  0.26940795,  0.04805693,
         0.83287076,  0.        ],
       [-1.26962211,  0.20327891,  1.52301925,  0.26940795, -1.29753719,
         0.36646313,  0.59160798],
       [ 1.19908755, -0.93508297, -1.79377823,  1.52664507,  0.04805693,
        -1.03275974, -0.59160798],
       [-0.28213825,  0.7724

In [ ]:
#knn 분류기 모델을 만든다.(=> 범주형 데이터를 예측하는 모델)
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [ ]:
#원래의 데이터를 넣어서 예측한다.
y_pred = classifier.predict(x)
y_pred

array(['1타입', '2타입', '2타입', '3타입', '1타입', '3타입', '1타입', '2타입', '3타입',
       '1타입', '3타입', '1타입', '2타입', '3타입'], dtype=object)

In [ ]:
y #원래 나왔던 값과 비교하기

array(['1타입', '2타입', '2타입', '3타입', '1타입', '3타입', '1타입', '2타입', '3타입',
       '1타입', '3타입', '1타입', '2타입', '3타입'], dtype=object)

In [ ]:
#모델을 평가한다.
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y, y_pred))
print(classification_report(y, y_pred))

[[5 0 0]
 [0 4 0]
 [0 0 5]]
             precision    recall  f1-score   support

        1타입       1.00      1.00      1.00         5
        2타입       1.00      1.00      1.00         4
        3타입       1.00      1.00      1.00         5

avg / total       1.00      1.00      1.00        14



=> 대각선 방향으로 숫자가 모여있을수록 정확한 모델이다  
정확도 : 100%