<a href="https://colab.research.google.com/github/Song-Hyunsub/Univ_Study/blob/main/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EC%9D%B4%ED%95%B4_%EC%8B%A4%EC%8A%B5/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_5%EC%B0%A8%EC%8B%9C_%ED%85%8C%EC%8A%A4%ED%8A%B8_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# 컬럼을 세팅합니다.
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# iris데이터를 읽어 옵니다.
dataset = pd.read_csv(url, names=names)

In [ ]:
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

In [ ]:
X , X.shape

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [ ]:
y , y.shape

(array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
        'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
        'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
        'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
        'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
        'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
        'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
        'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
        'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
        'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
        'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
        'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
        'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [ ]:
X_train

array([[5.5, 2.4, 3.8, 1.1],
       [4.6, 3.2, 1.4, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3. , 1.3, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 2. , 3.5, 1. ],
       [5.3, 3.7, 1.5, 0.2],
       [5.5, 2.6, 4.4, 1.2],
       [6.8, 3. , 5.5, 2.1],
       [5.8, 2.8, 5.1, 2.4],
       [6.3, 2.8, 5.1, 1.5],
       [5.1, 3.3, 1.7, 0.5],
       [6.3, 3.3, 6. , 2.5],
       [6.7, 3.1, 4.7, 1.5],
       [7.2, 3. , 5.8, 1.6],
       [6.9, 3.1, 5.1, 2.3],
       [6.2, 2.2, 4.5, 1.5],
       [4.7, 3.2, 1.6, 0.2],
       [6.2, 2.8, 4.8, 1.8],
       [4.9, 3.1, 1.5, 0.1],
       [4.8, 3.4, 1.9, 0.2],
       [6.4, 2.7, 5.3, 1.9],
       [4.8, 3.1, 1.6, 0.2],
       [6.1, 2.8, 4. , 1.3],
       [5.4, 3.9, 1.3, 0.4],
       [6. , 2.9, 4.5, 1.5],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 2.5, 4. , 1.3],
       [4.3, 3. , 1.1, 0.1],
       [6. , 3. , 4.8, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [4.7, 3.2, 1.3, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.3, 2.9, 5.6, 1.8],
       [5.7, 3

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() # 데이터를 정규화시킨다
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[-0.36443293, -1.47511122,  0.06506078, -0.11044784],
       [-1.48576504,  0.33808567, -1.30264023, -1.27989555],
       [-1.61035749, -1.70176083, -1.35962777, -1.14995692],
       [-1.73494995, -0.11521355, -1.35962777, -1.27989555],
       [-0.7382103 ,  0.79138489, -1.30264023, -1.27989555],
       [-0.98739521, -2.38170966, -0.10590185, -0.24038647],
       [-0.61361785,  1.47133373, -1.24565269, -1.27989555],
       [-0.36443293, -1.021812  ,  0.40698603,  0.0194908 ],
       [ 1.25526899, -0.11521355,  1.03384899,  1.18893851],
       [ 0.00934443, -0.56851277,  0.80589882,  1.57875441],
       [ 0.63230671, -0.56851277,  0.80589882,  0.4093067 ],
       [-0.86280276,  0.56473528, -1.1316776 , -0.89007965],
       [ 0.63230671,  0.56473528,  1.3187867 ,  1.70869305],
       [ 1.13067654,  0.11143606,  0.57794865,  0.4093067 ],
       [ 1.75363882, -0.11521355,  1.20481162,  0.53924533],
       [ 1.37986145,  0.11143606,  0.80589882,  1.44881578],
       [ 0.50771426, -1.

In [ ]:
#iris의 class를 예측하기 위하여 knn 적용하기

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)  # knn 적용(k=5)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [ ]:
#모델 만들기 완료
#그 후 X_test로 예측

In [ ]:
y_pred = classifier.predict(X_test)
y_pred

array(['Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica'], dtype=object)

In [ ]:
#다음은 혼돈행렬이다.
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 8  0  0]
 [ 0 12  1]
 [ 0  0  9]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         8
Iris-versicolor       1.00      0.92      0.96        13
 Iris-virginica       0.90      1.00      0.95         9

    avg / total       0.97      0.97      0.97        30

