<a href="https://colab.research.google.com/github/Song-Hyunsub/Univ_Study/blob/main/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EC%9D%B4%ED%95%B4_%EC%8B%A4%EC%8A%B5/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_18%EC%B0%A8%EC%8B%9C_%ED%85%8C%EC%8A%A4%ED%8A%B8_%EB%A1%9C%EC%A7%80%EC%8A%A4%ED%8B%B1%ED%9A%8C%EA%B7%80%EB%B6%84%EC%84%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

col_names = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age', 'label']

# 당뇨병환자 데이터
pima = pd.read_csv("diabetes.csv", header=1, names=col_names)

In [ ]:
pima.head()

pregnant  glucose  bp  skin  insulin   bmi  pedigree  age  label
0         1       85  66    29        0  26.6     0.351   31      0
1         8      183  64     0        0  23.3     0.672   32      1
2         1       89  66    23       94  28.1     0.167   21      0
3         0      137  40    35      168  43.1     2.288   33      1
4         5      116  74     0        0  25.6     0.201   30      0

In [ ]:
feature_cols = ['pregnant', 'insulin', 'bmi', 'age','glucose','bp','pedigree']
X = pima[feature_cols]        # Features
y = pima.label                # Target variable

In [ ]:
X.head()

pregnant  insulin   bmi  age  glucose  bp  pedigree
0         1        0  26.6   31       85  66     0.351
1         8        0  23.3   32      183  64     0.672
2         1       94  28.1   21       89  66     0.167
3         0      168  43.1   33      137  40     2.288
4         5        0  25.6   30      116  74     0.201

In [ ]:
y.head()

0    0
1    1
2    0
3    1
4    0
Name: label, dtype: int64

In [ ]:
from sklearn.cross_validation import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [ ]:
X_train = np.array(X_train)[np.array(y_train) != 'Outcome']

C:\Users\USER\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if __name__ == '__main__':


In [ ]:
y_train = np.array(y_train)[np.array(y_train) != 'Outcome']

C:\Users\USER\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if __name__ == '__main__':


In [ ]:
X_train = X_train[0]

In [ ]:
y_train = y_train[0]

In [ ]:
X_train

array([[1.00e+01, 1.80e+02, 3.29e+01, ..., 1.01e+02, 7.60e+01, 1.71e-01],
       [1.00e+00, 1.45e+02, 3.45e+01, ..., 1.17e+02, 8.80e+01, 4.03e-01],
       [2.00e+00, 8.80e+01, 2.61e+01, ..., 9.50e+01, 5.40e+01, 7.48e-01],
       ...,
       [7.00e+00, 0.00e+00, 2.74e+01, ..., 1.14e+02, 6.40e+01, 7.32e-01],
       [6.00e+00, 0.00e+00, 3.38e+01, ..., 1.25e+02, 7.60e+01, 1.21e-01],
       [2.00e+00, 2.05e+02, 3.32e+01, ..., 1.29e+02, 7.40e+01, 5.91e-01]])

In [ ]:
y_train

array([0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,

In [ ]:
X_test = np.array(X_test)

In [ ]:
y_test = np.array(y_test)

In [ ]:
X_test

array([[8.000e+00, 2.310e+02, 3.760e+01, ..., 1.670e+02, 1.060e+02,
        1.650e-01],
       [5.000e+00, 0.000e+00, 2.680e+01, ..., 1.320e+02, 8.000e+01,
        1.860e-01],
       [7.000e+00, 1.750e+02, 3.050e+01, ..., 1.600e+02, 5.400e+01,
        5.880e-01],
       ...,
       [1.000e+00, 5.900e+01, 2.510e+01, ..., 9.000e+01, 6.200e+01,
        1.268e+00],
       [5.000e+00, 0.000e+00, 3.950e+01, ..., 1.060e+02, 8.200e+01,
        2.860e-01],
       [1.000e+01, 0.000e+00, 2.400e+01, ..., 1.150e+02, 9.800e+01,
        1.022e+00]])

In [ ]:
y_test

array([1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [ ]:
#위의 데이터를 기반으로 하여 로지스틱회귀모델을 만들어 보자. 어떻게 하면 될까요?

In [ ]:
from sklearn.linear_model import LogisticRegression

# 로지스틱회귀분석 모델을 만든다.
logreg = LogisticRegression()

In [ ]:
#모델을 훈련시키고 X_test로 예측을 하여 보자.
#예측값은 어떻게 나오는가? 실제와 비교를 하여보자.

In [ ]:
# 모델을 훈련시킨다.
logreg.fit(X_train , y_train)

# 만든 모델로 예측한다.
y_pred=logreg.predict(X_test)

In [ ]:
y_pred

array([1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [ ]:
y_test == y_pred

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False, False,
        True,  True,  True, False,  True,  True,  True, False, False,
        True,  True,  True, False,  True,  True, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True,  True,  True,  True, False,
       False,  True,  True,  True, False,  True,  True,  True, False,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True, False,  True, False,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True, False, False,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False,

In [ ]:
np.mean(y_test == y_pred)

0.8072916666666666

In [ ]:
#위의 결과를 토대로 하여 혼돈행렬을 만들어 보자.

In [ ]:
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[120,  11],
       [ 26,  35]], dtype=int64)