<a href="https://colab.research.google.com/github/Song-Hyunsub/Univ_Study/blob/main/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EC%9D%B4%ED%95%B4_%EC%8B%A4%EC%8A%B5/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_6%EC%B0%A8%EC%8B%9C_%ED%85%8C%EC%8A%A4%ED%8A%B8_%EB%82%98%EC%9D%B4%EB%B8%8C%EB%B2%A0%EC%9D%B4%EC%A6%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

X = np.random.randint(5, size=(6, 100))
y = np.array([1, 2, 3, 4, 5, 6])

In [2]:
X

array([[3, 4, 2, 0, 2, 1, 1, 3, 1, 2, 1, 2, 0, 4, 4, 2, 4, 1, 2, 4, 0, 4,
        0, 1, 0, 1, 3, 0, 3, 4, 2, 1, 4, 2, 1, 1, 2, 2, 1, 0, 1, 0, 4, 0,
        2, 0, 4, 4, 1, 4, 4, 2, 2, 2, 4, 3, 3, 3, 2, 4, 1, 4, 4, 3, 3, 4,
        3, 4, 3, 1, 3, 0, 0, 0, 3, 1, 0, 0, 0, 2, 0, 3, 3, 2, 0, 1, 0, 4,
        4, 1, 4, 3, 0, 3, 1, 2, 4, 0, 3, 3],
       [3, 3, 4, 3, 3, 2, 2, 2, 4, 3, 3, 2, 0, 2, 0, 1, 3, 4, 3, 2, 2, 0,
        1, 3, 4, 1, 2, 4, 3, 1, 4, 0, 1, 2, 0, 3, 3, 0, 2, 0, 1, 2, 0, 0,
        0, 1, 3, 0, 4, 0, 4, 4, 3, 0, 2, 1, 1, 2, 2, 0, 2, 2, 2, 3, 2, 3,
        4, 2, 3, 4, 2, 2, 2, 1, 0, 3, 4, 3, 4, 3, 2, 0, 4, 2, 1, 4, 4, 4,
        3, 0, 1, 1, 3, 3, 2, 0, 2, 4, 0, 2],
       [1, 3, 4, 2, 1, 3, 2, 2, 2, 2, 3, 0, 1, 0, 4, 3, 4, 0, 0, 3, 3, 0,
        2, 4, 2, 2, 2, 2, 4, 1, 1, 4, 4, 4, 1, 1, 0, 1, 4, 2, 0, 3, 1, 3,
        1, 4, 4, 3, 2, 2, 2, 3, 1, 1, 0, 2, 1, 4, 0, 2, 0, 3, 3, 4, 4, 2,
        4, 2, 2, 2, 1, 2, 0, 4, 4, 0, 4, 0, 1, 3, 4, 2, 4, 1, 2, 1, 0, 1,
        4, 2, 4, 1, 1,

In [ ]:
y

array([1, 2, 3, 4, 5, 6])

In [ ]:
#나이브 베이즈 모델을 만들고 위의 데이터를 훈련데이터로 삼아서 훈련

In [3]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB() # 나이브 베이즈 모델
clf.fit(X, y)

MultinomialNB()

In [ ]:
#4번째 데이터의 class를 예측

In [ ]:
print(clf.predict(X[3].reshape(1,100)))

[4]


In [ ]:
#전체 훈련데이터를 예측

In [ ]:
clf.predict(X)

array([1, 2, 3, 4, 5, 6])